// localstorage
const LOCALSTORAGE_KEY_USER_ID = 'LOCALSTORAGE_KEY_USER_ID'

const EVENTS = {
  // game
  GAME_START: 'GAME_START',
  GAME_STARTED: 'GAME_STARTED', 
  GAME_FROCE_ENDED: 'GAME_FROCE_ENDED',
  GAME_ENDED: 'GAME_ENDED',
  // message
  MESSAGE_ADD: 'MESSAGE_ADD',
  MESSAGE_ADDED: 'MESSAGE_ADDED',
  // member
  MEMBER_ADDED: 'MEMBER_ADDED',
  MEMBER_LEAVED: 'MEMBER_LEAVED',
  // raise
  MEMBER_RAISE: 'MEMBER_RAISE',
  MEMBER_RAISED: 'MEMBER_RAISED',
}

const SENDER_IDS = {
  SERVER: '-1',
  CLIENT: '0',
}

const MSG_TYPES = {
  SYSTEM_TEXT: 'SYSTEM_TEXT',
  TEXT: 'TEXT',
}


module.exports = {
  LOCALSTORAGE_KEY_USER_ID,
  EVENTS,
  SENDER_IDS,
  MSG_TYPES,
}