// localstorage
const LOCALSTORAGE_KEY_USER_ID = 'LOCALSTORAGE_KEY_USER_ID'

const events = {
  // game
  GAME_START: 'GAME_START',
  GAME_STARTED: 'GAME_STARTED', 
  GAME_FROCE_ENDED: 'GAME_FROCE_ENDED',
  GAME_ENDED: 'GAME_ENDED',
  // message
  MESSAGE_ADD: 'MESSAGE_ADD',
  MESSAGE_ADDED: 'MESSAGE_ADDED',
  // member
  MEMBER_ADDED: 'MEMBER_ADDED',
  MEMBER_LEAVED: 'MEMBER_LEAVED',
  // raise
  MEMBER_RAISE: 'MEMBER_RAISE',
  MEMBER_RAISED: 'MEMBER_RAISED',
}


module.exports = {
  LOCALSTORAGE_KEY_USER_ID,
  events,
}